name: AXT1800-test

on:
  workflow_run:
    workflows: ["Auto-Clean"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: "Manual package config lines, separated by newlines."
        required: false
        type: string
      TEST:
        description: "Only output the config file; do not compile firmware."
        default: false
        required: false
        type: boolean

permissions: write-all

jobs:
  config:
    name: ${{ matrix.CONFIG }}
    strategy:
      fail-fast: false
      matrix:
        CONFIG: [AXT1800]
        SOURCE: [yjy116/immortalwrt]
        BRANCH: [main]

    uses: ./.github/workflows/WRT-CORE.yml
    secrets: inherit
    with:
      WRT_CONFIG: ${{ matrix.CONFIG }}
      WRT_THEME: argon
      WRT_NAME: AXT1800
      WRT_SSID: AXT1800
      WRT_WORD: "77915558"
      WRT_IP: 192.168.8.1
      WRT_PW: none
      WRT_REPO: https://github.com/${{ matrix.SOURCE }}.git
      WRT_BRANCH: ${{ matrix.BRANCH }}
      WRT_SOURCE: ${{ matrix.SOURCE }}
      WRT_PACKAGE: ${{ inputs.PACKAGE }}
      WRT_TEST: ${{ inputs.TEST }}
